### ISSUE TITLE
(Minor - Phone) Support Buttons look weird on landscape.

### ISSUE THREAD

**Issue by ArthurMacTavish** [ArthurMacTavish/ArthurMacTavish.github.io#1]
![Screenshot_2023-11-02-07-34-29-04_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://github.com/ArthurMacTavish/ArthurMacTavish.github.io/assets/61770462/32343625-2a39-439b-ab9d-efa4dec5fe0d)

Yeah, got the point?

**Comment by ArthurMacTavish** [comment]
# Not a Permanent Fix, but this will do.

While it's true you can do something like this.

```css
.support .support-links button {
    padding-left: 24px;
    padding-right: 24px;
    text-align: center;

    border: black solid;
    border-radius: 8px;
    box-shadow: 4px 4px black;
    transition: 0.5s;
}

.support .support-links .paypal {
    background-color: #AFDCFF;
    width: 100%;
}
```

It causes width button inconsistencies, and it's (at least to me) worth of trade-off.

![127 0 0 1_5500_index html](https://github.com/ArthurMacTavish/ArthurMacTavish.github.io/assets/61770462/dfd69944-a120-47c8-a353-3d967d72e793) #
